apiVersion: v1
kind: Service
metadata:
  name: credit-card-service
  labels:
    app: credit-card-service
spec:
  selector:
    app: credit-card-service
  ports:
    - protocol: TCP
      port: 8081       # Kubernetes service port
      targetPort: 8081 # Spring Boot server.port
  type: ClusterIP
